gameConfigBasicSettingsView = { {
	click_function = "ToggleVenusWin",
	label = "Toggle Venus Win",
	tooltip = "Toggle whether Venus must be terraformed as well before the game ends.",
	function_owner = self,
	position = { -0.4, 0.15, 0.6 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.venusWin",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ChangeCorpAmount",
	label = "",
	tooltip = "Important Note (ignore it if you didn't touch the drafting settings):\n" .. "Drawing corps during any drafting phase will override this value.",
	function_owner = Global,
	position = { 0.35, 0.15, 0.6 },
	rotation = { 0, 0, 0 },
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
	color = { 0, 200 / 255, 255 / 255 },
	dynamicLabel = {
		base = "Corps to draw: ",
		value = "gameConfig.setup.corpsToDraw",
	},
}, {
	click_function = "ToggleSolarPhase",
	label = "Toggle Solar Phase",
	function_owner = self,
	position = { 1.1, 0.15, 0.6 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.solarPhase",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ChangeColonyAmount",
	label = "",
	function_owner = Global,
	position = { -0.4, 0.15, 0.2 },
	rotation = { 0, 0, 0 },
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
  color = { 0, 200 / 255, 255 / 255 },
	dynamicLabel = {
		base = "Colonies to draw: ",
		value = "gameConfig.setup.corpsToDraw",
	},
}, {
	click_function = "ToggleDraft",
	label = "Toggle Drafting",
	function_owner = self,
	position = { 0.35, 0.1, 0.2 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.drafting",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ToggleTimer",
	label = "Toggle Timer",
	function_owner = self,
	position = { 1.1, 0.15, 0.2 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.timer",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ToggleColonies",
	label = "Toggle Colonies",
	function_owner = self,
	position = { -0.4, 0.15, -0.2 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.colonies",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ToggleTurmoil",
	label = "Toggle Turmoil",
	function_owner = self,
	position = { 0.35, 0.15, -0.2 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.turmoil",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ToggleBigBox",
	label = "Toggle Big Box",
	function_owner = self,
	position = { 1.1, 0.15, -0.2 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.bigBox",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ToggleCorpEra",
	label = "Toggle Corporate Era",
	function_owner = self,
	position = { -0.4, 0.1, -0.6 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.corpEra",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "ToggleVenus",
	label = "Toggle Venus",
	function_owner = self,
	position = { 0.35, 0.15, -0.6 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.venus",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
}, {
	click_function = "TogglePrelude",
	label = "Toggle Prelude",
	function_owner = self,
	position = { 1.1, 0.15, -0.6 },
	rotation = { 0, 0, 0 },
	onIndex = "gameConfig.setup.prelude",
	width = 1500,
	height = 500,
	font_size = 165,
	scale = { 0.2, 1, 0.2 },
} }
