// Name with sanitized everything up to first '=' for subfolders, remove function too
export const GlobalLuaModel = {
  '0': 'ScriptMetadata',
  '1': 'TableHelpers',
  '2': 'BagProtector',
  '3': 'MathHelpers',
  '5': 'ZoneHelpers',
  '6': 'HexMapHelpers',
  '7': 'DescriptionInterpreterFunction',
  '8': 'SnapPointHelpers',
  '9': 'ButtonFunctions',
  '10': 'Colors',
  '11': 'MarsSenate',
  '12': 'OwnableObjects',
  '13': 'Resources',
  '14': 'Icons',
  '15': 'EventData',
  '16': 'Mapping',
  '17': 'Phases',
  '18': 'Mapfeatures',
  '19': 'MapSizes',
  '20': 'StandardMapGen',
  '21': 'RandomMapGenBase',
  '22': 'RandomMapGen',
  '23': 'StandardProjectTileData',
  '24': 'LoggingModes',
  '25': 'ProgrammableActionTokenData',
  '26': 'ExpansionCrossoverCards',
  '27': 'AwardData',
  '28': 'TimerData',
  '29': 'GlobalParameters',
  '30': 'BoardGameTileProperties',
  '31': 'TurmoilPartyData',
  '32': 'PlaymatButtons',
  '33': 'PreDefinedMapSettings',
  '34': 'DraftingData',
  '35': 'TP',
  '45': 'BoardProperties',
  '46': 'ColonySetup',
  '47': 'GameConfigViews',
  '53': 'TimerFunctions',
  '54': 'ChangeGlobalParamFunctions',
  '55': 'GameConfigFunctions',
  '58': 'AddBigBox',
  '59': 'MapGenerator',
  '60': 'UninteractableGUIDs',
  '61': 'Bags',
  '62': 'GameState',
  '63': 'UINames',
  '64': 'AntiLagBoard',
  '65': 'GetStartFunction',
  '66': 'GameObjectHelpers',
  '67': 'ScoringFunctions',
  '68': 'UpdateCubePositionsOnTerraformingBarFunction',
  '69': 'TagToResourceConversionMap',
  '70': 'TagSystem',
  '71': 'ObjectActivationSystemConfig',
  '72': 'CardActivationRules',
  '73': 'PlayerActionFunctions',
  '74': 'DealingInProgress',
  '75': 'DealOceanToPlayer',
  '76': 'ColonySystem',
  '77': 'ChangeRulingPartyFunction',
  '78': 'TurmoilReduceTRFunction',
  '79': 'TurmoilSetup',
  '80': 'ExtendPlayerActivationTableauFunction',
  '81': 'UpdatePlayerTagsViaObjectFunction',
  '82': 'ResearchPhaseFunctions',
  '83': 'GameMap',
  '84': 'MapGeneratorFunctions',
  '86': 'TimerButtons',
  '87': 'TimerFunctions',
  '88': 'Logging',
  '89': 'ObjectActivationEffects',
  '90': 'PaymentSystem',
  '91': 'SpecialMilestones',
  '92': 'MilestoneData',
  '93': 'MilestoneAndAwardFunctions',
  '96': 'GlobalParameterSystem',
  '97': 'AresFunctions',
  '98': 'TerraformingParametersMap',
  '99': 'GameEventHandling',
  '100': 'OnLoadSave',
  '101': 'DoubleClickTable',
  '102': 'Randomizer'
}

export function getReverseLuaMap(): {[key: string]: string} {
  let rev: {[key: string]: string} = {};
  for(let k in GlobalLuaModel) {
    rev[(GlobalLuaModel as any)[k]] = k;
  }
  return rev;
}
